[package]
name = "ba_api"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.5", features = ["json", "socks"] }
ring = { version = "0.16.20" }
tokio = { version = "1.14.0", features = ["net", "macros", "fs"] }
tokio-tungstenite = { version = "0.16", features = ["native-tls"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
hex = "0.4.3"
thiserror = "1.0.30"
tracing = "0.1.29"
serde_urlencoded = "0.7.0"
futures-util = "0.3.17"
lazy_static = "1.4.0"
chrono = "0.4.19"

[dev-dependencies]
tokio = { version = "1.14.0", features = ["full"] }
tracing-subscriber = "0.3.3"

[lib]
doctest = false
